# Generated by Django 4.2.15 on 2024-08-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("image", models.ImageField(null=True, upload_to="images/")),
                ("price", models.IntegerField()),
                ("availability", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Storetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="itemsdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("quantity", models.FloatField()),
                ("tax", models.FloatField()),
                ("barcode", models.CharField(max_length=200)),
                ("county", models.CharField(max_length=50)),
                (
                    "items",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerceapp.items",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="items",
            name="stypetype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerceapp.storetype",
            ),
        ),
    ]
