# Generated by Django 4.2.15 on 2024-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0002_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blend_name", models.CharField(max_length=100)),
                ("roastery_name", models.CharField(max_length=100)),
                ("date_of_roasting", models.DateField()),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=300)),
                ("image_bag", models.ImageField(null=True, upload_to="images/")),
                ("image_notes", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
    ]
