# Generated by Django 4.2.15 on 2024-08-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0003_coffee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee",
            name="description",
            field=models.CharField(max_length=1000),
        ),
    ]
